[package]
name = "safe_lua"
version = "0.1.0"
authors = [" <raphael@rtpg.co>"]

[dependencies]
nom = "5.0.1"
nom-recursive = "0.1.1"
nom-packrat="0.3.0"
nom_locate="2.0.0"
lazy_static = "1.4.0"
argh = "0.1.4"
pretty_assertions = "0.6.1"
termion = "1.5.6"
